name: Build

on:
  schedule:
    - cron: '0 0 * * FRI'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@main
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt install qemu-utils bzip2

      - name: Build
        run: |
          sudo -E ./build-image.sh
          ls -hal
          sudo chown -fR $USER:$USER $PWD
          ls -hal
          wget --quiet https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && chmod +x /usr/local/bin/mc
          mc alias set sgp1 ${{ secrets.DOS_SGP1 }} ${{ secrets.DOS_KEY }} ${{ secrets.DOS_SECRET }} --api S3v4
          mc cp --recursive *.bz2 sgp1/tigefa/alpine/
          mc policy --recursive set puclic sgp1/tigefa/alpine/
          mc policy --recursive get sgp1/tigefa/alpine/
          mc policy --recursive list sgp1/tigefa/alpine/
          mc policy --recursive links sgp1/tigefa/alpine/

      - uses: actions/upload-artifact@main
        with:
          name: alpine-virt-image.qcow2.bz2
          path: "*.bz2"

      - name: Read version
        id: getversion
        run: echo "::set-output name=version::$(cat version)"

      - uses: marvinpinto/action-automatic-releases@latest
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: ${{ secrets.GH_PAT }}
          files: "*.bz2"
          automatic_release_tag: ${{ steps.getversion.outputs.version }}
          prerelease: false
